### ISSUE TITLE
deluge-gtk doesn't install libtorrent dependency

### ISSUE THREAD

**Issue by simonbcn** [ghostbsd/issues#17]
### Version

23.09.29

### Explain the issue and what happens

Installing `deluge-gtk` package does not install the `libtorrent-rasterbar` library.

### Explain how to reproduce the bug?

```
$ pkg search deluge
deluge-2.1.1,2                 Bittorrent client using Python, GTK3, and libtorrent-rasterbar
deluge-cli-2.1.1               CLI part of bittorrent client using Python and libtorrent-rasterbar
```

After installing deluge, I try to run it but:
```
$ deluge-gtk
16:34:13 [ERROR   ][deluge.ui.gtk3.gtkui              :1481] No libtorrent library found: Shared object "libtorrent-rasterbar.so.10.0.0" not found, required by "__init__.cpython-39.so"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deluge/_libtorrent.py", line 21, in <module>
    import deluge.libtorrent as lt
ModuleNotFoundError: No module named 'deluge.libtorrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deluge/_libtorrent.py", line 24, in <module>
    import libtorrent as lt
ImportError: Shared object "libtorrent-rasterbar.so.10.0.0" not found, required by "__init__.cpython-39.so"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deluge/ui/gtk3/gtkui.py", line 309, in _on_reactor_start
    client.start_standalone()
  File "/usr/local/lib/python3.9/site-packages/deluge/ui/client.py", line 637, in start_standalone
    self._daemon_proxy = DaemonStandaloneProxy(self.__event_handlers)
  File "/usr/local/lib/python3.9/site-packages/deluge/ui/client.py", line 458, in __init__
    from deluge.core import daemon
  File "/usr/local/lib/python3.9/site-packages/deluge/core/daemon.py", line 19, in <module>
    from deluge.core.core import Core
  File "/usr/local/lib/python3.9/site-packages/deluge/core/core.py", line 26, in <module>
    from deluge._libtorrent import LT_VERSION, lt
  File "/usr/local/lib/python3.9/site-packages/deluge/_libtorrent.py", line 26, in <module>
    raise LibtorrentImportError('No libtorrent library found: %s' % (ex))
deluge.error.LibtorrentImportError: No libtorrent library found: Shared object "libtorrent-rasterbar.so.10.0.0" not found, required by "__init__.cpython-39.so"
You have built the Boost library with thread support.
```

**Comment by ericbsd** [comment]
From what I see, it is in the list of dependencies to install.

```
> pkg search deluge
deluge-2.1.1,2                 Bittorrent client using Python, GTK3, and libtorrent-rasterbar
deluge-cli-2.1.1               CLI part of bittorrent client using Python and libtorrent-rasterbar
ericbsd@ericbsed-ghostbsd-pc /u/h/ericbsd> sudo pkg install -n deluge
Updating GhostBSD repository catalogue...
GhostBSD repository is up to date.
All repositories are up to date.
The following 34 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	deluge: 2.1.1,2
	deluge-cli: 2.1.1
	evdev-proto: 5.8
	fluidsynth: 2.3.4
	libmodplug: 0.8.9.1.r461
	libtorrent-rasterbar: 1.2.18,2
	opusfile: 0.12_1
	py39-Automat: 20.2.0
	py39-attrs: 23.1.0
	py39-bcrypt: 3.2.2
	py39-beaker: 1.12.1
	py39-boost-libs: 1.83.0
	py39-chardet: 4.0.0,1
	py39-constantly: 15.1.0
	py39-game: 2.5.1
	py39-h2: 4.0.0
	py39-hpack: 4.0.0
	py39-hyperframe: 6.0.0
	py39-hyperlink: 21.0.0_1
	py39-incremental: 21.3.0
	py39-libtorrent-rasterbar: 1.2.19,2
	py39-mako: 1.2.4
	py39-priority1: 1.3.0
	py39-pyasn1: 0.5.0
	py39-pyasn1-modules: 0.3.0
	py39-pyserial: 3.5_2
	py39-rencode: 1.0.6_1
	py39-service_identity: 18.1.0
	py39-twisted: 23.8.0
	py39-zope.interface: 5.3.0
	sdl2_mixer: 2.6.3_1
	sdl2_ttf: 2.20.2
	smpeg: 0.4.4_17
	v4l_compat: 1.23.0_2

Number of packages to be installed: 34

The process will require 127 MiB more space.
21 MiB to be downloaded.
```

**Comment by ericbsd** [comment]
I just installed it, and there is no error.

![Image](https://github.com/ghostbsd/issues/assets/4249848/e66c70c2-5e18-43ca-a808-d235964550ae)

Also, it is listed in the list of dependencies on FreshPorts  https://www.freshports.org/net-p2p/deluge-cli#dependencies

**Comment by ericbsd** [comment]
I am closing there is nothing to fix.
