### ISSUE TITLE
Software Station & Update Station over XRDP

### ISSUE THREAD

**Issue by brianthehughes** [ghostbsd/issues#206]
### Version

24.10.1

### What desktop?

Official MATE

### Explain the issue and what happens

Update Station does not notify of available updates if connected via XRDP.

Cannot start either Software Station or Update Station when connected via XRDP.

### Explain how to reproduce the bug?

brian@black32 ~> sudo software-station
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

/usr/local/bin/software-station:35: DeprecationWarning: 'crypt' is deprecated and slated for removal in Python 3.13
  import crypt
Traceback (most recent call last):
  File "/usr/local/bin/software-station", line 955, in <module>
    confirmation(user)
  File "/usr/local/bin/software-station", line 920, in __init__
    Gtk.Window.__init__(self)
  File "/usr/local/lib/python3.11/site-packages/gi/overrides/Gtk.py", line 519, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.

**brian@black32 ~ [1]> sudo update-station**
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

(update-station:98333): Gtk-CRITICAL **: 08:48:23.252: _gtk_css_lookup_resolve: assertion '(((__extension__ ({ GTypeInstance *__inst = (GTypeInstance*) ((provider)); GType __t = ((_gtk_style_provider_private_get_type ())); gboolean __r; if (!__inst) __r = (0); else if (__inst->g_class && __inst->g_class->g_type == __t) __r = (!(0)); else __r = g_type_check_instance_is_a (__inst, __t); __r; }))))' failed
/usr/local/lib/python3.11/site-packages/update_station/notification.py:72: Warning: g_object_set_data_full: assertion 'G_IS_OBJECT (object)' failed
  self.menu = Gtk.Menu()

(update-station:98333): Gtk-ERROR **: 08:48:23.254: Can't create a GtkStyleContext without a display connection
fish: Job 1, 'sudo update-station' terminated by signal SIGTRAP (Trace or breakpoint trap)

### What is the Expected behavior (if applicable)

Same operations as normal.
Or
Default superuser password prompt for remote (non Seat:0) connection.

**Comment by brianthehughes** [comment]
Adding networkmgr failure when working over XRDP

It launches as user, but user is not authorized to make configuration changes.

When launching with sudo, same **Authorization required, but no authorization protocol specified** error as Software/Update Station.
